# Generated by Django 5.2.8 on 2025-11-16 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pixStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('ispb', models.CharField(max_length=8)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ispb', 'ativo'], name='pixbackend__ispb_df864d_idx')],
            },
        ),
    ]
