# Generated by Django 5.2.8 on 2025-11-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixbackend', '0002_pixstream'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pixstream',
            name='pixbackend__ispb_df864d_idx',
        ),
        migrations.RemoveField(
            model_name='pixstream',
            name='ultimo_acesso',
        ),
    ]
