# Generated by Django 5.2.8 on 2025-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixbackend', '0003_remove_pixstream_pixbackend__ispb_df864d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixstream',
            old_name='interaction_id',
            new_name='iteration_id',
        ),
        migrations.AlterField(
            model_name='pix',
            name='dado_visualizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pix',
            name='recebedor_ispb',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
